version: "3.4"

services:
  app:
    image: "uber/prototool:1.8.1"
    environment:
      - GH_TOKEN
      - TRAVIS_BRANCH
      - TRAVIS_COMMIT
    volumes:
      - ".:/work"

  release:
    image: "climbcomp/semantic-release:15.13.21"
    environment:
      - GH_TOKEN
      - TRAVIS
      - TRAVIS_BRANCH
      - TRAVIS_COMMIT
      - TRAVIS_COMMIT_RANGE
      - TRAVIS_PULL_REQUEST
    volumes:
      - ".:/app"
